name: otp_input_editor
description: otp_input_editor empowers users to effortlessly edit OTPs from any position within the input field With customizable features.
version: 0.0.8
homepage: https://github.com/vidya-hub/otp_input_editor/blob/main/README.md
repository: https://github.com/vidya-hub/otp_input_editor.git
environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
